packages:
  - "sveltekit-app"
  - "studio"
allowBuilds:
  canvas: set this to true or false
  esbuild: true
minimumReleaseAgeExclude:
  - '@sanity/diff@5.28.0'
  - '@sanity/mutator@5.28.0'
  - '@sanity/presentation-comlink@2.1.0'
  - '@sanity/schema@5.28.0'
  - '@sanity/types@5.28.0'
  - '@sanity/util@5.28.0'
  - '@sanity/vision@5.28.0'
  - sanity@5.28.0
