/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MobileVideo = {
  poster?: Poster;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Poster = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "mobileVideo.poster.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type StackedGallery = {
  _type: "stackedGallery";
  items?: Array<{
    columnSpan?: ColumnSpan;
    image?: ElementImage;
    _type: "itemImage";
    _key: string;
  }>;
};

export type Info = {
  _type: "info";
  title?: string;
  content?: BlockContent;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  animationTop?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  animationBottom?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  email?: string;
  phone?: string;
  social?: Array<
    {
      _key: string;
    } & LinkExternal
  >;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type PageBuilder = {
  _type: "pageBuilder";
  sections?: Array<
    | ({
        _key: string;
      } & StackedGallery)
    | ({
        _key: string;
      } & Info)
  >;
};

export type Media = {
  _type: "media";
  image?: ElementImage;
  video?: ElementVideo;
};

export type AboutReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "about";
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type LookbookReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lookbook";
};

export type CaseStudiesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudies";
};

export type LinkInternal = {
  _type: "linkInternal";
  label?: string;
  url?:
    | AboutReference
    | HomeReference
    | LookbookReference
    | CaseStudiesReference;
};

export type CaseStudies = {
  _id: string;
  _type: "caseStudies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Lookbook = {
  _id: string;
  _type: "lookbook";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  stackedGallery?: StackedGallery;
  callFranco?: CallFranco;
};

export type CallFranco = {
  _type: "callFranco";
  content?: BlockContent;
  cta?: Cta;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pushingKeyframes?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  cover?: Media;
  heading?: BlockContent;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  aboutSection?: {
    heading?: BlockContent;
    paragraphOne?: BlockContent;
    paragraphTwo?: BlockContent;
    cta?: Cta;
    animation?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  clientsSection?: {
    title?: string;
    subtitle?: BlockContent;
    logos?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "logo";
      _key: string;
    }>;
  };
  endingBlock?: {
    animation?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    title?: string;
    description?: BlockContent;
    cta?: Cta;
  };
  callFranco?: CallFranco;
};

export type Cta = {
  _type: "cta";
  ctaType?: "linkInternal" | "linkExternal" | "linkEmail";
  linkInternal?: LinkInternal;
  linkExternal?: LinkExternal;
  linkEmail?: LinkEmail;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    | ({
        _key: string;
      } & LinkEmail)
    | ({
        _key: string;
      } & LinkExternal)
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  portrait?: ElementImage;
  intro?: {
    heading?: BlockContent;
    content?: BlockContent;
    earlyCareer?: BlockContent;
    workExperience?: BlockContent;
    cta?: Cta;
  };
  collaborations?: {
    heading?: BlockContent;
    content?: BlockContent;
    brands?: Array<string>;
    agencies?: Array<string>;
    animation?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  hobbies?: Array<string>;
  skillsSection?: {
    heading?: string;
    content?: BlockContent;
    skills?: Array<
      {
        _key: string;
      } & Info
    >;
  };
  reviewsSection?: {
    heading?: string;
    content?: BlockContent;
    reviews?: Array<{
      author?: string;
      companyRole?: string;
      content?: BlockContent;
      _type: "review";
      _key: string;
    }>;
  };
  callFranco?: CallFranco;
};

export type ElementImage = {
  _type: "elementImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  hasMobile?: boolean;
  mobileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LinkEmail = {
  _type: "linkEmail";
  label?: string;
  url?: string;
};

export type LinkExternal = {
  _type: "linkExternal";
  label?: string;
  url?: string;
};

export type ElementVideo = {
  _type: "elementVideo";
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  hasMobile?: boolean;
  mobileVideo?: MobileVideo;
};

export type ColumnSpan = {
  _type: "columnSpan";
  input?: "12" | "6" | "4";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  isHighlighted?: boolean;
  years?: string;
  coverImages?: {
    one?: ElementImage;
    two?: ElementImage;
  };
  shortSummary?: BlockContent;
  cover?: ElementImage;
  tagline?: BlockContent;
  description?: BlockContent;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  problem?: BlockContent;
  solution?: BlockContent;
  pageBuilder?: PageBuilder;
  result?: {
    content?: BlockContent;
    media?: Media;
  };
  credits?: Array<{
    label?: string;
    name?: string;
    _type: "credit";
    _key: string;
  }>;
  seo?: Seo;
};

export type Character = {
  _id: string;
  _type: "character";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  cover?: ElementImage;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MobileVideo
  | SanityImageAssetReference
  | Poster
  | StackedGallery
  | Info
  | SanityFileAssetReference
  | Settings
  | Seo
  | PageBuilder
  | Media
  | AboutReference
  | HomeReference
  | LookbookReference
  | CaseStudiesReference
  | LinkInternal
  | CaseStudies
  | Slug
  | Lookbook
  | CallFranco
  | ProjectReference
  | Home
  | Cta
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | About
  | ElementImage
  | LinkEmail
  | LinkExternal
  | ElementVideo
  | ColumnSpan
  | Service
  | ServiceReference
  | Project
  | Character
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sveltekit-app/src/lib/sanity/queries.ts
// Variable: homeQuery
// Query: {  "home": *[_type == "home"][0] {    ...,    featuredProjects[]->{      title,      slug,      coverImages,      services[]->{      title      },      shortSummary    },    clientsSection {      ...,      logos[]{      asset->      }    }  },  "characters": *[_type == "character"]}
export type HomeQueryResult = {
  home: {
    _id: string;
    _type: "home";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    pushingKeyframes?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    cover?: Media;
    heading?: BlockContent;
    featuredProjects: Array<{
      title: string | null;
      slug: Slug | null;
      coverImages: {
        one?: ElementImage;
        two?: ElementImage;
      } | null;
      services: Array<{
        title: string | null;
      }> | null;
      shortSummary: BlockContent | null;
    }> | null;
    aboutSection?: {
      heading?: BlockContent;
      paragraphOne?: BlockContent;
      paragraphTwo?: BlockContent;
      cta?: Cta;
      animation?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    };
    clientsSection: {
      title?: string;
      subtitle?: BlockContent;
      logos: Array<{
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }> | null;
    } | null;
    endingBlock?: {
      animation?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      title?: string;
      description?: BlockContent;
      cta?: Cta;
    };
    callFranco?: CallFranco;
  } | null;
  characters: Array<{
    _id: string;
    _type: "character";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    cover?: ElementImage;
  }>;
};

// Source: ../sveltekit-app/src/lib/sanity/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0]
export type AboutQueryResult = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  portrait?: ElementImage;
  intro?: {
    heading?: BlockContent;
    content?: BlockContent;
    earlyCareer?: BlockContent;
    workExperience?: BlockContent;
    cta?: Cta;
  };
  collaborations?: {
    heading?: BlockContent;
    content?: BlockContent;
    brands?: Array<string>;
    agencies?: Array<string>;
    animation?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  hobbies?: Array<string>;
  skillsSection?: {
    heading?: string;
    content?: BlockContent;
    skills?: Array<
      {
        _key: string;
      } & Info
    >;
  };
  reviewsSection?: {
    heading?: string;
    content?: BlockContent;
    reviews?: Array<{
      author?: string;
      companyRole?: string;
      content?: BlockContent;
      _type: "review";
      _key: string;
    }>;
  };
  callFranco?: CallFranco;
} | null;

// Source: ../sveltekit-app/src/lib/sanity/queries.ts
// Variable: caseStudiesQuery
// Query: *[_type == "project"]{  title,  slug  }
export type CaseStudiesQueryResult = Array<{
  title: string | null;
  slug: Slug | null;
}>;

// Source: ../sveltekit-app/src/lib/sanity/queries.ts
// Variable: lookbookQuery
// Query: *[_type == "lookbook"][0]
export type LookbookQueryResult = {
  _id: string;
  _type: "lookbook";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  stackedGallery?: StackedGallery;
  callFranco?: CallFranco;
} | null;

// Source: ../sveltekit-app/src/lib/sanity/queries.ts
// Variable: projectQuery
// Query: *[_type == "project" && defined(slug.current) && slug.current == $slug][0] {  ...,  services[]->,  "next": *[_type == "project" && defined(slug.current) && orderRank > ^.orderRank] | order(orderRank asc)[0]{  "orderRank": ^.orderRank,    title,    slug,    cover  },  "firstProject": *[_type == "project" && defined(slug.current)]| order(orderRank asc)[0]{    title,    slug,    cover  },  "projectIndexes": *[_type == "project"] | order(orderRank asc) {    slug  }  }
export type ProjectQueryResult = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  isHighlighted?: boolean;
  years?: string;
  coverImages?: {
    one?: ElementImage;
    two?: ElementImage;
  };
  shortSummary?: BlockContent;
  cover?: ElementImage;
  tagline?: BlockContent;
  description?: BlockContent;
  services: Array<{
    _id: string;
    _type: "service";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
  }> | null;
  problem?: BlockContent;
  solution?: BlockContent;
  pageBuilder?: PageBuilder;
  result?: {
    content?: BlockContent;
    media?: Media;
  };
  credits?: Array<{
    label?: string;
    name?: string;
    _type: "credit";
    _key: string;
  }>;
  seo?: Seo;
  next: {
    orderRank: string | null;
    title: string | null;
    slug: Slug | null;
    cover: ElementImage | null;
  } | null;
  firstProject: {
    title: string | null;
    slug: Slug | null;
    cover: ElementImage | null;
  } | null;
  projectIndexes: Array<{
    slug: Slug | null;
  }>;
} | null;

// Source: ../sveltekit-app/src/lib/sanity/queries.ts
// Variable: layoutQuery
// Query: {  "settings": *[_type == "settings"][0],  "caseStudies": *[_type == "project"]{  slug  }}
export type LayoutQueryResult = {
  settings: {
    _id: string;
    _type: "settings";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    animationTop?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    animationBottom?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    email?: string;
    phone?: string;
    social?: Array<
      {
        _key: string;
      } & LinkExternal
    >;
  } | null;
  caseStudies: Array<{
    slug: Slug | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "home": *[_type == "home"][0] {\n    ...,\n    featuredProjects[]->{\n      title,\n      slug,\n      coverImages,\n      services[]->{\n      title\n      },\n      shortSummary\n    },\n    clientsSection {\n      ...,\n      logos[]{\n      asset->\n      }\n    }\n  },\n  "characters": *[_type == "character"]\n}\n': HomeQueryResult;
    '*[_type == "about"][0]': AboutQueryResult;
    '*[_type == "project"]{\n  title,\n  slug\n  }': CaseStudiesQueryResult;
    '*[_type == "lookbook"][0]': LookbookQueryResult;
    '*[_type == "project" && defined(slug.current) && slug.current == $slug][0] {\n  ...,\n  services[]->,\n  "next": *[_type == "project" && defined(slug.current) && orderRank > ^.orderRank] | order(orderRank asc)[0]{\n  "orderRank": ^.orderRank,\n    title,\n    slug,\n    cover\n  },\n  "firstProject": *[_type == "project" && defined(slug.current)]| order(orderRank asc)[0]{\n    title,\n    slug,\n    cover\n  },\n  "projectIndexes": *[_type == "project"] | order(orderRank asc) {\n    slug\n  }\n  }': ProjectQueryResult;
    '{\n  "settings": *[_type == "settings"][0],\n  "caseStudies": *[_type == "project"]{\n  slug\n  }\n}': LayoutQueryResult;
  }
}
